version: 2
updates:
  # Enable version updates for pub dev
  - package-ecosystem: "pub"
    directory: "/src"
    # Check the pub registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
      include: "scope"
